"use server";

import type { Metadata } from "next";
import { redirect } from 'next/navigation';

import { validateRequest } from '@/core/auth';

import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();

  if (!user) {
    return redirect('/login');
  }

  return (
    {children}
  );
}
